//@ sourceMappingURL=Errors.map
// Generated by CoffeeScript 1.6.0
(function() {
  var CodedError, Errors;

  CodedError = function(message, code) {
    var error;
    error = new Error(message);
    error.name = "CodedError";
    error.code = code;
    error.__proto__ = CodedError.prototype;
    return error;
  };

  CodedError.prototype.__proto__ = Error.prototype;

  module.exports = Errors = {
    CodedError: CodedError
  };

}).call(this);
