//@ sourceMappingURL=HttpApiController.map
// Generated by CoffeeScript 1.6.0
(function() {
  var DrainManager, HttpApiController, WebsocketLoadBalancer, logger;

  WebsocketLoadBalancer = require("./WebsocketLoadBalancer");

  DrainManager = require("./DrainManager");

  logger = require("logger-sharelatex");

  module.exports = HttpApiController = {
    sendMessage: function(req, res, next) {
      var payload, _i, _len, _ref;
      logger.log({
        message: req.params.message
      }, "sending message");
      if (Array.isArray(req.body)) {
        _ref = req.body;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          payload = _ref[_i];
          WebsocketLoadBalancer.emitToRoom(req.params.project_id, req.params.message, payload);
        }
      } else {
        WebsocketLoadBalancer.emitToRoom(req.params.project_id, req.params.message, req.body);
      }
      return res.send(204);
    },
    startDrain: function(req, res, next) {
      var io, rate;
      io = req.app.get("io");
      rate = req.query.rate || "4";
      rate = parseFloat(rate) || 0;
      logger.log({
        rate: rate
      }, "setting client drain rate");
      DrainManager.startDrain(io, rate);
      return res.send(204);
    }
  };

}).call(this);
