//@ sourceMappingURL=RedisClientManager.map
// Generated by CoffeeScript 1.6.0
(function() {
  var RedisClientManager, logger, redis,
    __slice = [].slice;

  redis = require("redis-sharelatex");

  logger = require('logger-sharelatex');

  module.exports = RedisClientManager = {
    createClientList: function() {
      var clientList, configs, redisType, x;
      configs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      clientList = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = configs.length; _i < _len; _i++) {
          x = configs[_i];
          if (!(x != null)) {
            continue;
          }
          redisType = x.cluster != null ? "cluster" : x.sentinels != null ? "sentinel" : x.host != null ? "single" : "unknown";
          logger.log({
            redis: redisType
          }, "creating redis client");
          _results.push(redis.createClient(x));
        }
        return _results;
      })();
      return clientList;
    }
  };

}).call(this);
