//@ sourceMappingURL=SafeJsonParse.map
// Generated by CoffeeScript 1.6.0
(function() {
  var Settings, logger;

  Settings = require("settings-sharelatex");

  logger = require("logger-sharelatex");

  module.exports = {
    parse: function(data, callback) {
      var parsed;
      if (callback == null) {
        callback = function(error, parsed) {};
      }
      if (data.length > (Settings.max_doc_length || 2 * 1024 * 1024)) {
        logger.error({
          head: data.slice(0, 1024)
        }, "data too large to parse");
        return callback(new Error("data too large to parse"));
      }
      try {
        parsed = JSON.parse(data);
      } catch (e) {
        return callback(e);
      }
      return callback(null, parsed);
    }
  };

}).call(this);
